apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort | default 32100 }}
      targetPort: 8080
  selector:
    app: {{ include "hello-world.name" . }}